version: '3.8'

services:
    database:
        image: mariadb:10.11
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "33306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: funix_cars
            TZ: UTC
        volumes:
            - "database-data:/var/lib/mysql"

volumes:
    database-data:
        driver: local
